name: Continuous Integration Workflow

on:
  push:
    branches:
      - 'main'
      - 'ci'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      trading-postgres:
        image: postgres:13
        env:
          POSTGRES_HOST: trading-postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_TESTDB: testdb
          POSTGRES_USER: root
          POSTGRES_PASSWORD: "000000"
        ports:
          - 5672:5672

    env:
      SUBSCRIBE_MODE: "ws"
      FIRST_TASK_START: "2024-07-01"
      API_KEY: ${{ secrets.API_KEY }}

      POSTGRES_HOST: trading-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_TESTDB: testdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "000000"

    container:
      image: golang:1.21.0-bookworm

    steps:
      - name: < Checkout to Source Code >
        uses: actions/checkout@v3

      - name: < Run Unit Test >
        run: go test ./... -p 1 -parallel 1 -coverprofile cover.out && go tool cover -func=cover.out

      - name: Extract coverage percentage
        id: extract_coverage
        run: |
          echo "Test Coverage: $(go tool cover -func=cover.out | grep total)" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    steps:
      - name: < Checkout to Source Code >
        uses: actions/checkout@v3

      - name: < Set up QEMU >
        uses: docker/setup-qemu-action@v3

      - name: < Setup Docker Buildx >
        uses: docker/setup-buildx-action@v2

      - name: < Build Image and Push to Registry >
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          push: false
